spring:
    application:
        name: gateway-service
server:
    port: 80
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:3000/eureka/
zuul:
  ribbon:
    eager-load:
      enabled: true
  routes:
    user:
      path: /api/user/**
      serviceId: user-service
    stock:
      path: /api/stock/**
      serviceId: stock-service
    trade:
      path: /api/trade/**
      serviceId: trade-service
    web:
      path: /**
      serviceId: web-service